# Custom Language File for Launcher Customizer

[ejs.app]
title = "Shadow World Launcher"

[ejs.landing]
mediaGitHubURL = "#"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/ueuEAYAeuf"

[ejs.settings]
sourceGithubLink = ""
supportLink = ""

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR SHADOW WORLD"
welcomeDescription = "Entrez dans l'ombre, où la lumière ne peut pas vous suivre... Bienvenue dans Shadow World, où les ténèbres cachent des secrets et les héros sont faits pour être forgés."
welcomeDescCTA = "Vous n'êtes qu'à quelques clics de Shadow World."
